### ISSUE TITLE
Excluded should have a more specific name

### ISSUE THREAD

**Issue by hzsweers** [uber-common/rave#35]
Started using this a bit, and the more I see it the more I think it should be called something like `@ExcludedFromRAVE`. `@Excluded` by itself is very vague and not obvious at all. Thoughts for changing this in RAVE 2.0?

**Comment by naturalwarren** [comment]
This seems reasonable to me. That being said `@Excluded` can only be used on a class annotated `@Validated` which should help provide a little bit of context albeit not much to someone whose never used RAVE.

@behroozkhorashadi Thoughts?

**Comment by hzsweers** [comment]
> That being said `@Excluded` can only be used on a class annotated `@Validated` which should help provide a little bit of context albeit not much to someone whose never used RAVE.

Our model classes have quite a bit of other annotations, the validated annotation is usually pretty far from the excluded ones

**Comment by behroozkhorashadi** [comment]
I think excluded is fine because it is in the RAVE package.

**Comment by hzsweers** [comment]
It's used always outside the pckage though. In a model decorated with support annotations, json qualifiers, etc, having something that just generically says "Excluded" begs the question: "Excluded from what?"
