### ISSUE TITLE
Recommended proguard settings

### ISSUE THREAD

**Issue by allenchen1154** [uber-common/rave#45]
Since `Rave.getValidatorInstance()` relies on reflection to create an instance of our `ValidatorFactory` subclass, we had to add a line like 
```
-keep class * implements com.uber.rave.ValidatorFactory
```
to our proguard settings. Since proguard obfuscation is commonly used in Android apps, perhaps this should be added to the README?

**Comment by naturalwarren** [comment]
That's a good point. Thank Allen. Perhaps we want a proguard-rules.txt like they have in Butterknife:

https://github.com/JakeWharton/butterknife/blob/master/butterknife/proguard-rules.txt

**Comment by naturalwarren** [comment]
And proguard rules can only be shipped in an AAR. I'll update the README. Thanks Allen.
